### ISSUE TITLE
'Save As PDF' & 'Save As HTML' truncates exported file after a space is encountered.

### ISSUE THREAD

**Issue by elliotj** [shd101wyy/atom-markdown-katex#10]
Awesome package!

Invoking the 'Save As PDF' or 'Save As HTML' features export fine however, the filename of the exported version is truncated after a space is encountered;

'2016-04-04 - This File.md' ends up exported as '2016-04-04.pdf'

Thanks for your work!

**Comment by shd101wyy** [comment]
@elliotj Thanks for you reply!

I will let you know once I fixed this bug.

;)

**Comment by shd101wyy** [comment]
Hi @elliotj , the problem you that mentioned above is fixed ;)

Thanks for using this package `~(*_*)~`

**Comment by elliotj** [comment]
Hey, super good!

Thank you, for what you do.

ej
☎ (204) 230-1355 (Call or Text)
✉ elliotj@elliotj.com
