### ISSUE TITLE
Fail to correctly skip meta symbols in katex

### ISSUE THREAD

**Issue by RogerChern** [shd101wyy/atom-markdown-katex#16]
Something like 
{ parse error: p_{\text{BCC_A2}}=0.40 }

Certainly the _ symbol in BCC_A2 is not correctly skipped. I am wondering if this is a bug of the markdown engine or just a bug of katex itself.

Thank you for your efforts in making the scientific writing in atom more enjoyable. ;)

**Comment by shd101wyy** [comment]
Hello @RogerChern , thanks for your reply.

Is it convenient for you to attach a screenshot here so that I can see the issue more clearly.

:)

**Comment by RogerChern** [comment]
Hello @shd101wyy , I've successfully reproduced the bug in vanilla katex by the code below. I think the situation I just encontered is [this bug](https://github.com/Khan/KaTeX/issues/432) of katex. Please close this issue and wait for the katex team to fix it.

```
<!DOCTYPE html>
<html>
	<head>
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.5.1/katex.min.css">
		<script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.5.1/katex.min.js"></script>
	</head>
	<body>
		<div id="bug"></div>
		<script>katex.render("p_{\\text{BCC_A2}}=0.40", document.getElementById("bug"))</script>
	</body>
</html>
```

**Comment by shd101wyy** [comment]
@RogerChern Thank you very much.

**Comment by shd101wyy** [comment]
Hi, @RogerChern  I just added **MathJax** support for this package
Switching to **MathJax** should fix this issue.
You can set the math rendering method in the settings panel.
However, **MathJax** renders slower than **KaTeX**.

![screen shot 2016-05-13 at 4 14 38 pm](https://cloud.githubusercontent.com/assets/1908863/15262089/d0fb97d4-1925-11e6-9467-4bf55bde5f3c.png)

Cheers.

**Comment by RogerChern** [comment]
That's absolutely awesome!
