### ISSUE TITLE
How to write sentence with 2 $ signs?

### ISSUE THREAD

**Issue by abhayghatpande** [shd101wyy/atom-markdown-katex#2]
I have to write the sentence:

 ... product market has been valued at over $1.7 billion in 2013 and is expected to grow over $94 billion by 2024 ...

But the expression between the 2 $ signs gets rendered as TeX (math).
If I escape the $ signs with \$, it is all right, but then I get \$ in the HTML and PDF instead.

How to fix this?

**Comment by shd101wyy** [comment]
Thanks for telling me this issue ;)
I will fix this bug as soon as possible.

**Comment by shd101wyy** [comment]
Hi, the bug should have been fixed ;)
Please delete the package and then reinstall it. 

Sorry for the trouble

Please inform me if u find any other bugs ;)
