### ISSUE TITLE
这是bug嘛

### ISSUE THREAD

**Issue by Ahoge1993** [shd101wyy/atom-markdown-katex#21]
![bug1](https://cloud.githubusercontent.com/assets/7978344/14982203/463a4ffc-1167-11e6-9ef7-cb168b69e55b.png)
![bug2](https://cloud.githubusercontent.com/assets/7978344/14982205/463e0020-1167-11e6-891d-8efa53cd51ae.png)
一模一样的东西 然后发生了这样的事情。。这是bug嘛
![bug3](https://cloud.githubusercontent.com/assets/7978344/14982204/463cc9e4-1167-11e6-8203-b254483e9bc5.png)
然后我希望最后得到的结果应该是这样。这是我用别的工具生成的

**Comment by Ahoge1993** [comment]
`>$$y(n)+\sum_{l=1}^N a_l(n-l) = \sum_{m=0}^M b_mx(n-m)$$
>$$H(e^{j\omega}) = \frac{\sum_{m=0}^M b_m e^{-j\omega m}}{1+\sum_{l=1}^N a_l e^{-j\omega l}}$$


3.8
>$$H_d(e^{j\omega})=
\begin{cases}
1e^{-j\alpha \omega},&\lvert \omega \rvert \le \omega _ c\\
0,&\omega _c \lt \lvert \omega \rvert \le \pi
\end{cases}$$

利用IDTFT关系式求得
>$$x(n) \stackrel{\Delta}=\mathcal F^{-1}[X(e^{j \omega})]$$
`
附上我测试的东西。然后还有一个问题后面的字变成粉红色是什么情况。。

**Comment by shd101wyy** [comment]
Hi @Ahoge1993 ，我刚刚试了下，这个貌似是 **KaTeX** 的 bug。**KaTeX** 现在有很多数学符号不支持，例如 `\stackrel`。我可能以后改用 **MathJax**

非常抱歉，我修复好了会 @ 你，估计得两周后，因为我期末了。。。

**Comment by shd101wyy** [comment]
@Ahoge1993  我刚刚发了个新版本，升级了下 KaTeX，你可以更新下。
然后关于你上面的式子，你可以这么打

```
$$y(n)+\sum_{l=1}^N a_l(n-l) = \sum_{m=0}^M b_mx(n-m)$$

$$H(e^{j\omega}) = \frac{\sum_{m=0}^M b_m e^{-j\omega m}}{1+\sum_{l=1}^N a_l e^{-j\omega l}}$$

$$
H_d(e^{j\omega})=
  \begin{cases}
    1e^{-j\alpha \omega},&\lvert \omega \rvert \le \omega_c\ \\
    0, &\omega_c \lt \lvert \omega \rvert \le \pi
  \end{cases}
$$

$$x(n) \triangleq{\Delta}=\mathcal F^{-1}[X(e^{j \omega})]$$
```

```\stackrel``` 依然是不支持的，所以这里可以用 `\triangleq` 来代替。

谢谢

**Comment by Ahoge1993** [comment]
@shd101wyy 感谢你的更新！谢谢

**Comment by Ahoge1993** [comment]
![bug1](https://cloud.githubusercontent.com/assets/7978344/15003445/8cdf9e54-11de-11e6-9fba-797ace987f62.png)
我用你给的测试结果是这样 所以大括号以前是不支持吗？

**Comment by shd101wyy** [comment]
@Ahoge1993 
我运行出来的结果是这样的？你升级到最新的 `0.5.7` 版本了吗？

![screen shot 2016-05-03 at 9 14 37 pm](https://cloud.githubusercontent.com/assets/1908863/15003686/2def22b2-1174-11e6-9455-e2ca23a6d319.png)

**Comment by Ahoge1993** [comment]
是的我更新到了最新版
![bug1](https://cloud.githubusercontent.com/assets/7978344/15004067/1db117ae-11e5-11e6-9484-b6304680acf9.png)
![bug2](https://cloud.githubusercontent.com/assets/7978344/15004068/1db3ea60-11e5-11e6-9d10-e2dead70dcbe.png)

**Comment by shd101wyy** [comment]
我刚刚用 windows 10 试了下，貌似也没有问题。
<img width="960" alt="default" src="https://cloud.githubusercontent.com/assets/1908863/15004408/4a4c18e0-117c-11e6-979f-13c8f36286ff.PNG">
**所以我觉得你可以试试:**
1. 重启编辑器。
2. 如果重启编辑器没用的话，就卸载这个 package 然后重新安装试试
3. 如果还不行我就很迷了 (T_T)，这个周末我再看看。抱歉

**Comment by Ahoge1993** [comment]
@shd101wyy 重启之后搞定了 谢谢
