### ISSUE TITLE
打开md预览中的网页链接，总是会打开一个多余的浏览器页面

### ISSUE THREAD

**Issue by MrJasper** [shd101wyy/atom-markdown-katex#24]
如题。也就是点击一次链接打开两个页面而不是一个。
浏览器为Chrome 版本 50.0.2661.94 m
ATOM 版本 1.7.3
atom-markdown-katex 版本 0.5.8

**Comment by shd101wyy** [comment]
Hi, @MrJasper 。多谢发现这个 bug。
应该已经修复了，如果还有问题请给我回复~

谢谢！
