### ISSUE TITLE
How can I change the font family?

### ISSUE THREAD

**Issue by Camypaper** [shd101wyy/atom-markdown-katex#3]
Hello, I love this cool plugin.
I want to know the way to change the font family.

**Comment by shd101wyy** [comment]
Thanks for your reply, 

Right now you can change the font family by pressing ```cmd+shit+p``` and then select ```Markdown Katex Preview: Customize CSS ```. Then you can change the ```font-family``` in ```.markdown-katex-preview``` section. After modifying the font family, you need to restart atom to see the change.

I  will provide a easier way to change the css style in the future.

**Comment by Camypaper** [comment]
Thank you for your reply. I solve it!

**Comment by shd101wyy** [comment]
Hi, 

I have just improved the way of customizing markdown style in ```version 0.3.8```. You can still use ```Markdown Katex Preview: Customize CSS``` command to make custom style. After ```version 0.3.8``` you don't have to restart atom every time to see changes. Please tell me if you find any further bugs ;)

Thank you

**Comment by neesonqk** [comment]
I'm unable to find this `Markdown Katex Preview: Customize CSS` via `cmd+shift+p`?
