### ISSUE TITLE
Uncaught TypeError: Cannot read property 'setScrollTop' of null

### ISSUE THREAD

**Issue by wxflogic** [shd101wyy/atom-markdown-katex#5]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: [atom-markdown-katex](https://github.com/shd101wyy/atom-markdown-katex) package, v0.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'setScrollTop' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:362

TypeError: Cannot read property 'setScrollTop' of null
    at atom-text-editor.TextEditorElement.setScrollTop (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:362:28)
    at TextEditor.module.exports.TextEditor.setScrollTop (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2991:46)
    at HTMLDivElement.markdownHtmlView.onscroll (/Users/wxf/.atom/packages/atom-markdown-katex/lib/md-preview.js:167:26)
```

### Commands

```
  2x -1:45.3.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:44.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:41.4.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:41.1.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -1:36.5.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:34.8.0 core:move-down (atom-text-editor.editor.is-focused)
  4x -1:33.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:20.9.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:20.7.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:17.1.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:16.7.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:13 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  2x -0:30.4.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:25.9.0 markdown-writer:insert-new-line (atom-text-editor.editor.is-focused)
     -0:07.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:03.1.0 tree-view:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "markdown-preview",
      "ever-notedown",
      "markdown-preview-plus",
      "my-package",
      "latex-completions"
    ],
    "projectHome": "/Users/wxf/Documents/github"
  }
}
```

### Installed Packages

```coffee
# User
atom-markdown-katex, v0.4.0
autocomplete-bibtex, v0.6.2
language-latex, v0.6.1
language-pfm, v0.82.0
latex, v0.29.0
latex-plus, v0.8.3
latexer, v0.2.7
linter, v1.11.3
markdown-folder, v0.5.0
markdown-table-formatter, v2.7.2
markdown-writer, v2.3.1
mathjax-wrapper, v0.1.0
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by shd101wyy** [comment]
Hi @wxflogic, do you still get the issue after you restart the atom editor?

**Comment by wxflogic** [comment]
Not any more after restarting. Thanks for your fantastic work.

p.s. I'd like to have the theme of the preview the same as the
one-dark-theme. How can I customize it?

Yiyi Wang <notifications@github.com>于2016年2月18日周四 上午9:56写道：

**Comment by shd101wyy** [comment]
I will try to support that feature in the future.

**Comment by wxflogic** [comment]
Thanks. I look forward to it very much.

Yiyi Wang <notifications@github.com>于2016年2月18日周四 上午11:23写道：

**Comment by shd101wyy** [comment]
Hi @wxflogic , I just uploaded a new version of this package, and the feature that you request is now supported ;) 

Below is the one-dark-theme snapshot
![snip20160301_2](https://cloud.githubusercontent.com/assets/1908863/13419706/de5cac2a-df45-11e5-9ab8-c60cda8a913f.png)

Go ahead and upgrade your package! If you meet any problem while upgrading, please try to delete the package first then reinstall it.

If you change your editor theme, then the preview theme will change accordingly.

Please report any bug that you find.

Thanks ;)

**Comment by wxflogic** [comment]
Thank you for informing this new feature. It's fantastic!

Yiyi Wang <notifications@github.com>于2016年3月1日周二 下午2:41写道：
