### ISSUE TITLE
Updating failed

### ISSUE THREAD

**Issue by nick41496** [shd101wyy/atom-markdown-katex#6]
Updating to the latest version fails with the following error. On a Surface Book running Windows 10 and Atom version 1.5.3.
> Updating to “atom-markdown-katex@0.4.1” failed.Hide output…
> 
> oniguruma@5.1.2 install C:\Users\USERNAME\AppData\Local\Temp\apm-install-dir-11621-7508-1vcyjd9\node_modules\atom-markdown-katex\node_modules\highlights\node_modules\first-mate\node_modules\oniguruma
> node-gyp rebuild
> 
> 
> C:\Users\USERNAME\AppData\Local\Temp\apm-install-dir-11621-7508-1vcyjd9\node_modules\atom-markdown-katex\node_modules\highlights\node_modules\first-mate\node_modules\oniguruma>if not defined npm_config_node_gyp (node "C:\Users\USERNAME\AppData\Local\atom\app-1.5.3\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 
> 
> npm WARN engine escodegen@1.8.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
> npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
> npm ERR! Windows_NT 6.2.9200
> npm ERR! argv "C:\\Users\\USERNAME\\AppData\\Local\\atom\\app-1.5.3\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\USERNAME\\AppData\\Local\\atom\\app-1.5.3\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\USERNAME\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\USERNAME\\.atom\\.apmrc" "install" "C:\\Users\\USERNAME\\AppData\\Local\\Temp\\d-11621-7508-svhq4t\\package.tgz" "--target=0.34.5" "--arch=ia32"
> npm ERR! node v0.10.40
> npm ERR! npm  v2.13.3
> npm ERR! code ELIFECYCLE
> 
> npm ERR! oniguruma@5.1.2 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the oniguruma@5.1.2 install script 'node-gyp rebuild'.
> npm ERR! This is most likely a problem with the oniguruma package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls oniguruma
> npm ERR! There is likely additional logging output above.
>

**Comment by shd101wyy** [comment]
Hi @nick41496 , I just uploaded version 0.4.2. 
It should work on Windows now!
