### ISSUE TITLE
Github Flavored Markdown & Syntax Highlighting

### ISSUE THREAD

**Issue by DominikGuzei** [shd101wyy/atom-markdown-katex#7]
Hey there, thanks for this awesome plugin!
Do you think you could make it compatible with Github flavored markdown and syntax highlighting?

**Comment by shd101wyy** [comment]
Hi @DominikGuzei, you can change to Github flavored markdown through the setting panel.

https://raw.githubusercontent.com/shd101wyy/atom-markdown-katex/master/screenshot/settings.png

I don't know whether that is what you want or not :)

**Comment by DominikGuzei** [comment]
Hey @shd101wyy!
I already have enabled this and the general style works great – it's only the code examples that have no syntax highlighting.

Here is how it looks like with `atom-markdown-katex`:
![bildschirmfoto 2016-03-24 um 08 58 54](https://cloud.githubusercontent.com/assets/172414/14011429/aa455610-f19e-11e5-928e-8e625c05d32e.png)

And here with the standard markdown preview:
![bildschirmfoto 2016-03-24 um 08 58 49](https://cloud.githubusercontent.com/assets/172414/14011430/b299f53c-f19e-11e5-9806-5cf0b543ebfc.png)

Im using the Github-style code highlighting in markdown like this:
```` ```javascript … ``` ````

**Comment by shd101wyy** [comment]
Thanks @DominikGuzei, 

I am now traveling in UK and I will go back to US after a week. So I will have a look at the code after I go back :)

Sorry for the trouble.

**Comment by shd101wyy** [comment]
Hey @DominikGuzei ,

Is it convenient for you to send me your markdown file content ? Because  ` javascript `works fine when I try it.

<img width="702" alt="default" src="https://cloud.githubusercontent.com/assets/1908863/14033653/0fa4570e-f1ea-11e5-8cfb-45dbe237e3e8.PNG">

Thanks

**Comment by DominikGuzei** [comment]
Yeah sure, here is some snippet from my code:

    ### Question 1.1 – Declarations

    ```javascript
    a = 1;
    var b = 2;
    let c = 3;
    const d = 4
    ```
    What is the effect of each declaration and when would you use which?

    **Answers:**

    * no keyword:
    * `var`:
    * `let`:
    * `const`:

**Comment by shd101wyy** [comment]
Hi @DominikGuzei , what Syntax Theme are you using?
When I tried your snippet with Monokai theme, it rendered correctly.

![snip20160327_1](https://cloud.githubusercontent.com/assets/1908863/14069122/efd7b0f6-f45a-11e5-8c72-ac38ccb029a3.png)

**Comment by DominikGuzei** [comment]
Ah thanks, now i have some control over the syntax highlighting in the preview :wink: was using the "no caffein" theme which was just grey in this case. But the strange thing is that the PDF output included a very nice syntax highlighting … it was just missing in the preview!

**Comment by shd101wyy** [comment]
I think I have figured out what caused the problem.
I will try to upload a new version by the end of this week :)

**Comment by shd101wyy** [comment]
@DominikGuzei Done `~(*_*)~`

Thanks!

**Comment by DominikGuzei** [comment]
Works like a charm now! :wink: thanks so much!
